### ISSUE TITLE
Expose no sync option

### ISSUE THREAD

**Issue by oskarth** [vacp2p/mvds#56]
Have an option that allows retransmissions etc to be turned off. Similar to IP and flag for UDP/TCP, and Matrix PDU/EDU(~).

This means there's less direct coupling with Whisper and we give clients freedom to have a less heavy mode of operation if they care less about reliability such as for typing notifications, discovery mechanisms, pings, etc.

How this framing is best done might vary. This issue might also live elsewhere. Capturing it here now though.

**Comment by decanus** [comment]
So there are a few clarifications we need to make here.

1. Should this flag be node specific, or message specific?
2. If I say no to retransmission, does that mean that `OFFER` along with the `MESSAGE` will not be retransmitted or only the `OFFER` when in interactive mode and only the `MESSAGE` when in batch mode.
3. How do we handle `REQUEST` do we allow for those not to be retransmitted too? if so how?

**Comment by decanus** [comment]
solved through `Metadata.ephemeral` field.
