### ISSUE TITLE
Persistency for MVDS

### ISSUE THREAD

**Issue by adambabik** [vacp2p/mvds#63]
### Problem

Currently, mvds implements storage only in memory, however, for the production use cases we need persistent storage. 

### Solution

There are a few components that require some sort of storage. We need to identify which require persistence storage.

| Component |  Persistency | Implemented |
|-------------|-------------|--------------|
| Peers           | Yes                | No                  |
| States          | Yes               | No                  |
| Messages (`store/` dir)    | Yes               | No                  |
| Payloads     | No                 | No                |
| Epoch          | Yes               | No                 |

@decanus please let me know if this table is correct and I will start working on the persistency with sqlite.

cc @cammellos

**Comment by decanus** [comment]
@adambabik These components look accurate to me, one thing that also needs to be saved is the epoch. I have an issue for that here: https://github.com/status-im/status-console-client/issues/120

**Comment by adambabik** [comment]
@decanus thanks, updated the table.
